site_description: "FairyGUI - Professional UI editor, cross-platform UI solution"
site_keywords: "FairyGUI,FGUI,UI Editor"
site_index_description: "Professional UI editor, cross-platform UI solution"
root_domain: github.com
fairygui_version: 3.0
